export const chartTypes = [
  "Vertical Bar Chart",
  "Horizontal Bar Chart",
  "Line Chart",
  "Pie Chart",
  "Area Chart",
  "Histogram",
  "Scatter Plot",
  "Scatter Plot With Fit Line",
  "Scatter Plot With Multiple Fit Line",
  "Boxplot",
  "Vertical Stacked Bar Chart",
  "Horizontal Stacked Bar Chart",
  "Clustered Bar Chart",
  "Multiple Line Chart",
  "Error Bar Chart",
  "Stacked Area Chart",
  "Grouped Scatter Plot",
  "Dot Plot",
  "Population Pyramid",
  "Frequency Polygon",
  // "3D Bar Chart",
  "Clustered Error Bar Chart",
  "Scatter Plot Matrix",
  "Stacked Histogram",
  "Clustered Boxplot",
  "1-D Boxplot",
  "Simple Range Bar",
  "Clustered Range Bar",
  "High-Low-Close Chart",
  "Difference Area",
  "Vertical Bar & Line Chart",
  "Dual Axes Scatter Plot",
  "Drop Line Chart",
  "Summary Point Plot",
  // "3D Bar Chart2",
  // "Clustered 3D Bar Chart",
  // "Stacked 3D Bar Chart",
  // "3D Bar Chart",
  // "Bar2",
  // "3D Scatter Plot",
  // "Grouped 3D Scatter Plot",
  // "Word Cloud",
  // "Vertical Bar & Line Chart2",
  "Stem And Leaf Plot",
  "Violin Plot",
  "Density Chart",
  "Q-Q Plot",
  "P-P Plot",
  "3D Bar Chart (ECharts)",
  "3D Scatter Plot (ECharts)",
  "Clustered 3D Bar Chart (ECharts)",
  "Stacked 3D Bar Chart (ECharts)",
  "Grouped 3D Scatter Plot (ECharts)",
] as const;

export type ChartType = (typeof chartTypes)[number];
