import { processAndAddPlots } from '../utils/plotProcessor';
import { useResultStore } from '@/stores/useResultStore';
import { ChartService } from '@/services/chart/ChartService';
import { ExploreAnalysisParams } from '../types';
import { Variable } from '@/types/Variable';

// Mock dependencies
jest.mock('@/stores/useResultStore');
jest.mock('@/services/chart/ChartService');

const mockUseResultStore = useResultStore as jest.MockedFunction<typeof useResultStore>;
const mockChartService = ChartService as jest.Mocked<typeof ChartService>;

describe('plotProcessor', () => {
  const mockAddStatistic = jest.fn();
  
  beforeEach(() => {
    jest.clearAllMocks();
    
    // Mock useResultStore.getState()
    mockUseResultStore.getState = jest.fn().mockReturnValue({
      addStatistic: mockAddStatistic
    });
    
    // Mock ChartService.createChartJSON
    mockChartService.createChartJSON = jest.fn().mockReturnValue({
      data: [],
      options: {},
      metadata: { title: 'Test Chart' }
    });
    
    mockAddStatistic.mockResolvedValue(undefined);
  });

  const mockDepVar: Variable = {
    id: 1,
    name: 'testVar',
    label: 'Test Variable',
    type: 'numeric',
    measure: 'scale',
    role: 'input',
    width: 8,
    decimals: 2,
    values: {},
    missingValues: [],
    alignment: 'right',
    columnIndex: 0
  };

  const mockGroupedData = {
    all_data: {
      factorLevels: {},
      data: [
        [10], // columnIndex 0
        [20],
        [30],
        ['15-01-2024'], // Test date conversion
        ['20-02-2024']
      ]
    }
  };

  describe('processAndAddPlots', () => {
    it('should not create charts when no plot options are enabled', async () => {
      const params: ExploreAnalysisParams = {
        dependentVariables: [mockDepVar],
        factorVariables: [],
        labelVariable: null,
        confidenceInterval: '95',
        showDescriptives: true,
        showMEstimators: false,
        showOutliers: false,
        showPercentiles: false,
        boxplotType: 'none',
        showStemAndLeaf: false,
        showHistogram: false,
        showNormalityPlots: false
      };

      await processAndAddPlots(1, mockGroupedData, params);

      expect(mockChartService.createChartJSON).not.toHaveBeenCalled();
      expect(mockAddStatistic).not.toHaveBeenCalled();
    });

    it('should create histogram when showHistogram is true', async () => {
      const params: ExploreAnalysisParams = {
        dependentVariables: [mockDepVar],
        factorVariables: [],
        labelVariable: null,
        confidenceInterval: '95',
        showDescriptives: true,
        showMEstimators: false,
        showOutliers: false,
        showPercentiles: false,
        boxplotType: 'none',
        showStemAndLeaf: false,
        showHistogram: true,
        showNormalityPlots: false
      };

      await processAndAddPlots(1, mockGroupedData, params);

      expect(mockChartService.createChartJSON).toHaveBeenCalledWith({
        chartType: 'Histogram',
        chartData: expect.any(Array),
        chartMetadata: {
          title: 'testVar',
          description: 'Generated by Explore analysis'
        }
      });

      expect(mockAddStatistic).toHaveBeenCalledWith(1, {
        title: 'testVar',
        output_data: expect.any(String),
        components: 'Histogram',
        description: ''
      });
    });

    it('should create boxplot when boxplotType is not none', async () => {
      const params: ExploreAnalysisParams = {
        dependentVariables: [mockDepVar],
        factorVariables: [],
        labelVariable: null,
        confidenceInterval: '95',
        showDescriptives: true,
        showMEstimators: false,
        showOutliers: false,
        showPercentiles: false,
        boxplotType: 'dependents-separately',
        showStemAndLeaf: false,
        showHistogram: false,
        showNormalityPlots: false
      };

      await processAndAddPlots(1, mockGroupedData, params);

      expect(mockChartService.createChartJSON).toHaveBeenCalledWith({
        chartType: 'Boxplot',
        chartData: expect.any(Array),
        chartMetadata: {
          title: 'testVar',
          description: 'Generated by Explore analysis'
        }
      });

      expect(mockAddStatistic).toHaveBeenCalledWith(1, {
        title: 'testVar',
        output_data: expect.any(String),
        components: 'Boxplot',
        description: ''
      });
    });

    it('should create stem-and-leaf plot when showStemAndLeaf is true', async () => {
      const params: ExploreAnalysisParams = {
        dependentVariables: [mockDepVar],
        factorVariables: [],
        labelVariable: null,
        confidenceInterval: '95',
        showDescriptives: true,
        showMEstimators: false,
        showOutliers: false,
        showPercentiles: false,
        boxplotType: 'none',
        showStemAndLeaf: true,
        showHistogram: false,
        showNormalityPlots: false
      };

      await processAndAddPlots(1, mockGroupedData, params);

      expect(mockChartService.createChartJSON).toHaveBeenCalledWith({
        chartType: 'Stem And Leaf Plot',
        chartData: expect.any(Array),
        chartMetadata: {
          title: 'testVar',
          description: 'Generated by Explore analysis'
        }
      });

      expect(mockAddStatistic).toHaveBeenCalledWith(1, {
        title: 'testVar',
        output_data: expect.any(String),
        components: 'Stem And Leaf Plot',
        description: ''
      });
    });

    it('should handle multiple chart types simultaneously', async () => {
      const params: ExploreAnalysisParams = {
        dependentVariables: [mockDepVar],
        factorVariables: [],
        labelVariable: null,
        confidenceInterval: '95',
        showDescriptives: true,
        showMEstimators: false,
        showOutliers: false,
        showPercentiles: false,
        boxplotType: 'dependents-separately',
        showStemAndLeaf: true,
        showHistogram: true,
        showNormalityPlots: false
      };

      await processAndAddPlots(1, mockGroupedData, params);

      // Should create 3 charts: Boxplot, Histogram, Stem-and-Leaf
      expect(mockChartService.createChartJSON).toHaveBeenCalledTimes(3);
      expect(mockAddStatistic).toHaveBeenCalledTimes(3);

      // Verify chart types
      expect(mockChartService.createChartJSON).toHaveBeenCalledWith(
        expect.objectContaining({ chartType: 'Boxplot' })
      );
      expect(mockChartService.createChartJSON).toHaveBeenCalledWith(
        expect.objectContaining({ chartType: 'Histogram' })
      );
      expect(mockChartService.createChartJSON).toHaveBeenCalledWith(
        expect.objectContaining({ chartType: 'Stem And Leaf Plot' })
      );
    });

    it('should handle date string conversion in data', async () => {
      const params: ExploreAnalysisParams = {
        dependentVariables: [mockDepVar],
        factorVariables: [],
        labelVariable: null,
        confidenceInterval: '95',
        showDescriptives: true,
        showMEstimators: false,
        showOutliers: false,
        showPercentiles: false,
        boxplotType: 'none',
        showStemAndLeaf: false,
        showHistogram: true,
        showNormalityPlots: false
      };

      await processAndAddPlots(1, mockGroupedData, params);

      // Verify that ChartService was called with converted data
      const callArgs = mockChartService.createChartJSON.mock.calls[0][0];
      expect(callArgs.chartData).toEqual(expect.any(Array));
      expect(callArgs.chartData.length).toBeGreaterThan(0);
    });

    it('should handle empty data gracefully', async () => {
      const emptyGroupedData = {
        all_data: {
          factorLevels: {},
          data: []
        }
      };

      const params: ExploreAnalysisParams = {
        dependentVariables: [mockDepVar],
        factorVariables: [],
        labelVariable: null,
        confidenceInterval: '95',
        showDescriptives: true,
        showMEstimators: false,
        showOutliers: false,
        showPercentiles: false,
        boxplotType: 'none',
        showStemAndLeaf: false,
        showHistogram: true,
        showNormalityPlots: false
      };

      await processAndAddPlots(1, emptyGroupedData, params);

      // Should not create charts for empty data
      expect(mockChartService.createChartJSON).not.toHaveBeenCalled();
      expect(mockAddStatistic).not.toHaveBeenCalled();
    });

    it('should handle ChartService errors gracefully', async () => {
      // Mock ChartService to throw error
      mockChartService.createChartJSON.mockImplementation(() => {
        throw new Error('Chart creation failed');
      });

      const params: ExploreAnalysisParams = {
        dependentVariables: [mockDepVar],
        factorVariables: [],
        labelVariable: null,
        confidenceInterval: '95',
        showDescriptives: true,
        showMEstimators: false,
        showOutliers: false,
        showPercentiles: false,
        boxplotType: 'none',
        showStemAndLeaf: false,
        showHistogram: true,
        showNormalityPlots: false
      };

      // Should not throw error
      await expect(processAndAddPlots(1, mockGroupedData, params)).resolves.not.toThrow();
      
      // Should not call addStatistic if chart creation fails
      expect(mockAddStatistic).not.toHaveBeenCalled();
    });
  });
});