import type { ChartType } from "@/components/Modals/Graphs/ChartTypes";

export interface AxisConfig {
  label: boolean;
  min: boolean;
  max: boolean;
  majorIncrement: boolean;
  origin: boolean;
  [key: string]: boolean; // Add index signature for compatibility
}

export interface SingleYAxisConfig {
  x: AxisConfig;
  y: AxisConfig;
}

export interface DualYAxisConfig {
  x: AxisConfig;
  y1: AxisConfig;
  y2: AxisConfig;
}

export interface ThreeDAxisConfig {
  x: AxisConfig;
  y: AxisConfig;
  z: AxisConfig;
}

export interface ErrorBarTypeConfig {
  confidenceLevel?: boolean;
  multiplier?: boolean;
}

export interface ErrorBarConfig {
  ci?: ErrorBarTypeConfig;
  se?: ErrorBarTypeConfig;
  sd?: ErrorBarTypeConfig;
}

export interface ChartConfigOptions {
  title: boolean;
  subtitle: boolean;
  titleColor: boolean;
  subtitleColor: boolean;
  titleFontSize: boolean;
  subtitleFontSize: boolean;
  chartColors: boolean;
  axis: SingleYAxisConfig | DualYAxisConfig | ThreeDAxisConfig;
  statistic?: boolean;
  errorBar?: ErrorBarConfig;
  normalCurve?: boolean;
}

export const chartConfigOptions: Record<ChartType, ChartConfigOptions> = {
  "Vertical Bar Chart": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  Histogram: {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    normalCurve: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: false,
        max: false,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  Boxplot: {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
    },
  },
  "Pie Chart": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: false,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: false,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
    },
  },
  "Horizontal Bar Chart": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
      y: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
    },
  },
  "Line Chart": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Area Chart": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Scatter Plot": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Scatter Plot With Fit Line": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Scatter Plot With Multiple Fit Line": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Vertical Stacked Bar Chart": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Horizontal Stacked Bar Chart": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
      y: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
    },
  },
  "Clustered Bar Chart": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Multiple Line Chart": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Error Bar Chart": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    errorBar: {
      ci: {
        confidenceLevel: true,
      },
      se: {
        multiplier: true,
      },
      sd: {
        multiplier: true,
      },
    },
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Stacked Area Chart": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Grouped Scatter Plot": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Dot Plot": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Population Pyramid": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
    },
  },
  "Frequency Polygon": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Clustered Error Bar Chart": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    errorBar: {
      ci: {
        confidenceLevel: true,
      },
      se: {
        multiplier: true,
      },
      sd: {
        multiplier: true,
      },
    },
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Scatter Plot Matrix": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: false,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: false,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
    },
  },
  "Stacked Histogram": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Clustered Boxplot": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "1-D Boxplot": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: false,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Simple Range Bar": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Clustered Range Bar": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "High-Low-Close Chart": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Difference Area": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Vertical Bar & Line Chart": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y1: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
      y2: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Dual Axes Scatter Plot": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
      y1: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
      y2: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Drop Line Chart": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Summary Point Plot": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    statistic: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  // "3D Bar Chart2": {
  //   title: true,
  //   subtitle: true,
  //   titleColor: true,
  //   subtitleColor: true,
  //   titleFontSize: true,
  //   subtitleFontSize: true,
  //   chartColors: true,
  //   axis: {
  //     x: {
  //       label: true,
  //       min: true,
  //       max: true,
  //       majorIncrement: true,
  //       origin: false,
  //     },
  //     y: {
  //       label: true,
  //       min: true,
  //       max: true,
  //       majorIncrement: true,
  //       origin: false,
  //     },
  //   },
  // },
  "3D Bar Chart (ECharts)": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      z: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
    },
  },
  "Stacked 3D Bar Chart (ECharts)": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      z: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
    },
  },
  "Clustered 3D Bar Chart (ECharts)": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      z: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
    },
  },
  // "Clustered 3D Bar Chart": {
  //   title: true,
  //   subtitle: true,
  //   titleColor: true,
  //   subtitleColor: true,
  //   titleFontSize: true,
  //   subtitleFontSize: true,
  //   chartColors: true,
  //   axis: {
  //     x: {
  //       label: true,
  //       min: true,
  //       max: true,
  //       majorIncrement: true,
  //       origin: false,
  //     },
  //     y: {
  //       label: true,
  //       min: true,
  //       max: true,
  //       majorIncrement: true,
  //       origin: false,
  //     },
  //   },
  // },
  // "Stacked 3D Bar Chart": {
  //   title: true,
  //   subtitle: true,
  //   titleColor: true,
  //   subtitleColor: true,
  //   titleFontSize: true,
  //   subtitleFontSize: true,
  //   chartColors: true,
  //   axis: {
  //     x: {
  //       label: true,
  //       min: true,
  //       max: true,
  //       majorIncrement: true,
  //       origin: false,
  //     },
  //     y: {
  //       label: true,
  //       min: true,
  //       max: true,
  //       majorIncrement: true,
  //       origin: false,
  //     },
  //   },
  // },
  // "3D Scatter Plot": {
  //   title: true,
  //   subtitle: true,
  //   titleColor: true,
  //   subtitleColor: true,
  //   titleFontSize: true,
  //   subtitleFontSize: true,
  //   chartColors: true,
  //   axis: {
  //     x: {
  //       label: true,
  //       min: true,
  //       max: true,
  //       majorIncrement: true,
  //       origin: false,
  //     },
  //     y: {
  //       label: true,
  //       min: true,
  //       max: true,
  //       majorIncrement: true,
  //       origin: false,
  //     },
  //   },
  // },
  // "Grouped 3D Scatter Plot": {
  //   title: true,
  //   subtitle: true,
  //   titleColor: true,
  //   subtitleColor: true,
  //   titleFontSize: true,
  //   subtitleFontSize: true,
  //   chartColors: true,
  //   axis: {
  //     x: {
  //       label: true,
  //       min: true,
  //       max: true,
  //       majorIncrement: true,
  //       origin: false,
  //     },
  //     y: {
  //       label: true,
  //       min: true,
  //       max: true,
  //       majorIncrement: true,
  //       origin: false,
  //     },
  //   },
  // },
  "Stem And Leaf Plot": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: false,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: false,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
    },
  },
  "Violin Plot": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Density Chart": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "Q-Q Plot": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: true,
        max: true,
        majorIncrement: true,
        origin: false,
      },
    },
  },
  "P-P Plot": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
    },
  },
  "3D Scatter Plot (ECharts)": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      z: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
    },
  },
  "Grouped 3D Scatter Plot (ECharts)": {
    title: true,
    subtitle: true,
    titleColor: true,
    subtitleColor: true,
    titleFontSize: true,
    subtitleFontSize: true,
    chartColors: true,
    axis: {
      x: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      y: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
      z: {
        label: true,
        min: false,
        max: false,
        majorIncrement: false,
        origin: false,
      },
    },
  },
  // Tambahkan chart lain sesuai kebutuhan
};
