import type {
    OptScaCatpcaBootstrapType,
    OptScaCatpcaCategoryPlotsType,
    OptScaCatpcaDefineRangeScaleType,
    OptScaCatpcaDefineScaleType,
    OptScaCatpcaDiscretizeType,
    OptScaCatpcaLoadingPlotsType,
    OptScaCatpcaMainType,
    OptScaCatpcaMissingType,
    OptScaCatpcaObjectPlotsType,
    OptScaCatpcaOptionsType,
    OptScaCatpcaOutputType,
    OptScaCatpcaSaveType,
    OptScaCatpcaType,
} from "@/components/Modals/Analyze/dimension-reduction/optimal-scaling/catpca/types/optimal-scaling-captca";

export const OptScaCatpcaMainDefault: OptScaCatpcaMainType = {
    AnalysisVars: null,
    SuppleVars: null,
    LabelingVars: null,
    Dimensions: 2,
};

export const OptScaCatpcaDefineRangeScaleDefault: OptScaCatpcaDefineRangeScaleType =
    {
        Weight: 1,
        SplineOrdinal: true,
        SplineNominal: false,
        MultipleNominal: false,
        Ordinal: false,
        Nominal: false,
        Numeric: false,
        Degree: 2,
        InteriorKnots: 2,
    };

export const OptScaCatpcaDefineScaleDefault: OptScaCatpcaDefineScaleType = {
    SplineOrdinal: true,
    SplineNominal: false,
    MultipleNominal: false,
    Ordinal: false,
    Nominal: false,
    Numeric: false,
    Degree: 2,
    InteriorKnots: 2,
};

export const OptScaCatpcaDiscretizeDefault: OptScaCatpcaDiscretizeType = {
    VariablesList: null,
    Method: "Grouping",
    NumberOfCategories: true,
    NumberOfCategoriesValue: 7,
    DistributionNormal: true,
    DistributionUniform: false,
    EqualIntervals: false,
    EqualIntervalsValue: null,
};

export const OptScaCatpcaMissingDefault: OptScaCatpcaMissingType = {
    CurrentTargetList: null,
    AnalysisVariables: null,
    SupplementaryVariables: null,
    MissingValuesExclude: true,
    ExcludeMode: true,
    ExcludeExtraCat: false,
    ExcludeRandomCat: false,
    MissingValuesImpute: false,
    ImputeMode: true,
    ImputeExtraCat: false,
    ImputeRandomCat: false,
    ExcludeObjects: false,
};

export const OptScaCatpcaOptionsDefault: OptScaCatpcaOptionsType = {
    RangeOfCases: true,
    First: null,
    Last: null,
    SingleCase: false,
    SingleCaseValue: null,
    NormalizationMethod: "VariablePrincipal",
    NormCustomValue: null,
    Convergence: 0.00001,
    MaximumIterations: 100,
    VariableLabels: true,
    LimitForLabel: 20,
    VariableNames: false,
    PlotDimDisplayAll: true,
    PlotDimRestrict: false,
    PlotDimLoDim: null,
    PlotDimHiDim: null,
    ConfigurationMethod: "None",
    ConfigFile: null,
    None: true,
    Varimax: false,
    Oblimin: false,
    Delta: 0,
    Quartimax: false,
    Equimax: false,
    Promax: false,
    Kappa: 4,
    Kaiser: true,
};

export const OptScaCatpcaOutputDefault: OptScaCatpcaOutputType = {
    QuantifiedVars: null,
    LabelingVars: null,
    CatQuantifications: null,
    DescStats: null,
    ObjScoresIncludeCat: null,
    ObjScoresLabelBy: null,
    ObjectScores: false,
    CorreOriginalVars: false,
    ComponentLoadings: true,
    CorreTransVars: true,
    SortBySize: false,
    IterationHistory: false,
    Variance: false,
};

export const OptScaCatpcaSaveDefault: OptScaCatpcaSaveType = {
    Discretized: false,
    DiscNewdata: true,
    DiscDataset: null,
    DiscWriteNewdata: false,
    DiscretizedFile: null,
    SaveTrans: false,
    Trans: false,
    TransNewdata: true,
    TransDataset: null,
    TransWriteNewdata: false,
    TransformedFile: null,
    SaveObjScores: false,
    ObjScores: false,
    ObjNewdata: true,
    ObjDataset: null,
    ObjWriteNewdata: false,
    ObjScoresFile: null,
    SaveApprox: false,
    Approx: false,
    ApproxNewdata: true,
    ApproxDataset: null,
    ApproxWriteNewdata: false,
    ApproximationsFile: null,
    BTLoading: false,
    BTObject: false,
    BTCategories: false,
    BTEllipseCoord: false,
    BTNewDataset: true,
    BTDatasetName: null,
    BTWriteDataFile: false,
    BTFileText: null,
    All: true,
    First: false,
    MultiNomDim: null,
};

export const OptScaCatpcaBootstrapDefault: OptScaCatpcaBootstrapType = {
    PerformBT: false,
    Balanced: true,
    Unbalanced: false,
    NumberSamples: 1000,
    ConfLevel: 95,
    Procrustes: true,
    Reflection: false,
    ThresholdLoading: "Area",
    ThresholdObject: "MeanNStdDev",
    ThresholdCategory: "Area",
    OperatorLoading: "Greater",
    OperatorObject: "Greater",
    OperatorCategory: "Greater",
    ValueLoading: 0,
    ValueObject: 2,
    ValueCategory: 2,
    NumberPoints: 40,
};

export const OptScaCatpcaObjectPlotsDefault: OptScaCatpcaObjectPlotsType = {
    ObjectPoints: true,
    Biplot: false,
    BiLoadings: true,
    BiCentroids: false,
    Triplot: false,
    BTIncludeAllVars: true,
    BTIncludeSelectedVars: false,
    BTAvailableVars: null,
    BTSelectedVars: null,
    LabelObjLabelByCaseNumber: false,
    LabelObjLabelByVar: false,
    LabelObjAvailableVars: null,
    LabelObjSelectedVars: null,
};

export const OptScaCatpcaCategoryPlotsDefault: OptScaCatpcaCategoryPlotsType = {
    SourceVar: null,
    CatPlotsVar: null,
    JointCatPlotsVar: null,
    TransPlotsVar: null,
    DimensionsForMultiNom: 2,
    InclResidPlots: false,
    PrjCentroidsOfVar: null,
    PrjCentroidsOntoVar: null,
};

export const OptScaCatpcaLoadingPlotsDefault: OptScaCatpcaLoadingPlotsType = {
    Variance: false,
    DisplayCompLoadings: true,
    LoadingIncludeAllVars: true,
    LoadingIncludeSelectedVars: false,
    LoadingAvailableVars: null,
    LoadingSelectedVars: null,
    IncludeCentroids: false,
    IncludeCentroidsIncludeAllVars: true,
    IncludeCentroidsIncludeSelectedVars: false,
    IncludeCentroidsAvailableVars: null,
    IncludeCentroidsSelectedVars: null,
};

export const OptScaCatpcaDefault: OptScaCatpcaType = {
    main: OptScaCatpcaMainDefault,
    defineRangeScale: OptScaCatpcaDefineRangeScaleDefault,
    defineScale: OptScaCatpcaDefineScaleDefault,
    discretize: OptScaCatpcaDiscretizeDefault,
    missing: OptScaCatpcaMissingDefault,
    options: OptScaCatpcaOptionsDefault,
    output: OptScaCatpcaOutputDefault,
    save: OptScaCatpcaSaveDefault,
    bootstrap: OptScaCatpcaBootstrapDefault,
    objectPlots: OptScaCatpcaObjectPlotsDefault,
    categoryPlots: OptScaCatpcaCategoryPlotsDefault,
    loadingPlots: OptScaCatpcaLoadingPlotsDefault,
};
