import type { TourStep } from "../types";
import { TABS } from "../types";

export const baseTourSteps: TourStep[] = [
    {
        title: "Variable Selection",
        content: "Select variables from the available list to analyze with One-Way ANOVA. Only numeric variables are shown.",
        targetId: "one-way-anova-available-variables",
        defaultPosition: "bottom",
        defaultHorizontalPosition: null,
        icon: "📊",
        requiredTab: TABS.VARIABLES,
    },
    {
        title: "Test Variables",
        content:
            "Variables in this list will be analyzed. You can reorder them by dragging.",
        targetId: "one-way-anova-test-variables",
        defaultPosition: "bottom",
        defaultHorizontalPosition: "left",
        icon: "📋",
        requiredTab: TABS.VARIABLES,
    },
    {
        title: "Factor Variable",
        content: "Choose a categorical variable to act as the factor (grouping) variable. This variable determines how your data will be split into groups for comparison in the ANOVA. The analysis will compare the means of the selected test variables across the different groups defined by this factor.",
        targetId: "factor-variable-section",
        defaultPosition: "bottom",
        defaultHorizontalPosition: null,
        icon: "🔢",
        requiredTab: TABS.VARIABLES,
    },
    {
        title: "Estimate Effect Size",
        content: "This option is currently disabled as the effect size calculation feature is not yet available in this version. When implemented, it will allow you to include effect size calculations in your results.",
        targetId: "estimate-effect-size-section",
        defaultPosition: 'bottom',
        defaultHorizontalPosition: null,
        icon: "📏",
        requiredTab: TABS.VARIABLES,
    },
    {
        title: "Equal Variances Assumed",
        content: "Check this option to assume that the variances of the groups are equal. This is a common assumption in ANOVA, but it can be violated in some cases. If you are unsure, it is recommended to leave this option unchecked and let the analysis determine if the variances are equal.",
        targetId: "equal-variances-assumed-section",
        defaultPosition: 'bottom',
        defaultHorizontalPosition: null,
        icon: "🔍",
        requiredTab: TABS.POST_HOC
    },
    {
        title: "Statistics",
        content: "Select additional statistics to include in your ANOVA results, such as mean, standard deviation, and sample size for each group. These options affect the descriptive and summary statistics tables generated by the One-Way ANOVA analysis.",
        targetId: "statistics-section",
        defaultPosition: 'bottom',
        defaultHorizontalPosition: null,
        icon: "📊",
        requiredTab: TABS.OPTIONS
    }
];
