import type {
    UnivariateBootstrapType,
    UnivariateContrastType,
    UnivariateEMMeansType,
    UnivariateMainType,
    UnivariateModelType,
    UnivariateOptionsType,
    UnivariatePlotsType,
    UnivariatePostHocType,
    UnivariateSaveType,
    UnivariateType,
} from "@/components/Modals/Analyze/general-linear-model/univariate/types/univariate";

export const UnivariateMainDefault: UnivariateMainType = {
    DepVar: null,
    FixFactor: null,
    RandFactor: null,
    Covar: null,
    WlsWeight: null,
};

export const UnivariateModelDefault: UnivariateModelType = {
    NonCust: true,
    Custom: false,
    BuildCustomTerm: false,
    FactorsVar: null,
    TermsVar: null,
    FactorsModel: null,
    CovModel: null,
    RandomModel: null,
    BuildTermMethod: "interaction",
    TermText: null,
    SumOfSquareMethod: "typeIII",
    Intercept: true,
};

export const UnivariateContrastDefault: UnivariateContrastType = {
    FactorList: null,
    ContrastMethod: "none",
    Last: true,
    First: false,
};

export const UnivariatePlotsDefault: UnivariatePlotsType = {
    SrcList: null,
    AxisList: null,
    LineList: null,
    PlotList: null,
    FixFactorVars: null,
    RandFactorVars: null,
    LineChartType: true,
    BarChartType: false,
    IncludeErrorBars: false,
    ConfidenceInterval: true,
    StandardError: false,
    Multiplier: 2,
    IncludeRefLineForGrandMean: false,
    YAxisStart0: false,
};

export const UnivariatePostHocDefault: UnivariatePostHocType = {
    SrcList: null,
    FixFactorVars: null,
    ErrorRatio: 100,
    Twosided: true,
    LtControl: false,
    GtControl: false,
    CategoryMethod: "last",
    Waller: false,
    Dunnett: false,
    Lsd: false,
    Bonfe: false,
    Sidak: false,
    Scheffe: false,
    Regwf: false,
    Regwq: false,
    Snk: false,
    Tu: false,
    Tub: false,
    Dun: false,
    Hoc: false,
    Gabriel: false,
    Tam: false,
    Dunt: false,
    Games: false,
    Dunc: false,
};

export const UnivariateEMMeansDefault: UnivariateEMMeansType = {
    SrcList: null,
    TargetList: null,
    CompMainEffect: false,
    ConfiIntervalMethod: "lsdNone",
};

export const UnivariateSaveDefault: UnivariateSaveType = {
    UnstandardizedPre: false,
    WeightedPre: false,
    StdStatistics: false,
    CooksD: false,
    Leverage: false,
    UnstandardizedRes: false,
    WeightedRes: false,
    StandardizedRes: false,
    StudentizedRes: false,
    DeletedRes: false,
    CoeffStats: false,
    StandardStats: false,
    Heteroscedasticity: false,
    NewDataSet: true,
    FilePath: null,
    DatasetName: null,
    WriteNewDataSet: false,
};

export const UnivariateOptionsDefault: UnivariateOptionsType = {
    DescStats: false,
    HomogenTest: false,
    EstEffectSize: false,
    SprVsLevel: false,
    ObsPower: false,
    ResPlot: false,
    ParamEst: false,
    LackOfFit: false,
    TransformMat: false,
    GeneralFun: false,
    ModBruschPagan: false,
    FTest: false,
    BruschPagan: false,
    WhiteTest: false,
    ParamEstRobStdErr: false,
    HC0: false,
    HC1: false,
    HC2: false,
    HC3: false,
    HC4: false,
    CoefficientMatrix: false,
    SigLevel: 0.05,
};

export const UnivariateBootstrapDefault: UnivariateBootstrapType = {
    PerformBootStrapping: false,
    NumOfSamples: 1000,
    Seed: false,
    SeedValue: 200000,
    Level: 95,
    Percentile: true,
    BCa: false,
    Simple: true,
    Stratified: false,
    Variables: null,
    StrataVariables: null,
};

export const UnivariateDefault: UnivariateType = {
    main: UnivariateMainDefault,
    model: UnivariateModelDefault,
    contrast: UnivariateContrastDefault,
    plots: UnivariatePlotsDefault,
    posthoc: UnivariatePostHocDefault,
    emmeans: UnivariateEMMeansDefault,
    save: UnivariateSaveDefault,
    options: UnivariateOptionsDefault,
    bootstrap: UnivariateBootstrapDefault,
};
